<a href="https://colab.research.google.com/github/UmayaJayasuriya/PyTorch_Practice/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [100]:
!nvidia-smi

Thu Jan  8 05:30:29 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   37C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [101]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


##Introduction to Tensors

Creating tensors

In [102]:
#scalaar
scalar = torch.tensor(7)
scalar

tensor(7)

In [103]:
scalar.ndim

0

In [104]:
#get tensor back as python int
scalar.item()

7

In [105]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [106]:
vector.ndim

1

In [107]:
vector.shape

torch.Size([2])

In [108]:
#matrix
MATRIX = torch.tensor([[7,8,4],
                       [9,10,3]])
MATRIX

tensor([[ 7,  8,  4],
        [ 9, 10,  3]])

In [109]:
MATRIX.ndim

2

In [110]:
MATRIX[0]

tensor([7, 8, 4])

In [111]:
MATRIX.shape

torch.Size([2, 3])

In [112]:
#tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [113]:
TENSOR.ndim

3

In [114]:
TENSOR.shape

torch.Size([1, 3, 3])

In [115]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [116]:
TENSOR[0,1]

tensor([4, 5, 6])

In [117]:
TENSOR[0,1,2]

tensor(6)

In [118]:
TENSOR2 = torch.tensor([[[1,2],[2,3]],
                        [[3,4],[4,5]],
                         [[5,6],[6,7]]])
TENSOR2

tensor([[[1, 2],
         [2, 3]],

        [[3, 4],
         [4, 5]],

        [[5, 6],
         [6, 7]]])

In [119]:
TENSOR2[0,0,1]

tensor(2)

#Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [120]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9560, 0.3860, 0.9937, 0.3060],
        [0.4836, 0.1079, 0.3814, 0.4526],
        [0.3987, 0.4684, 0.4896, 0.8814]])

In [121]:
random_tensor.ndim

2

In [122]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) #height, width ,color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

#Zeros and Ones

In [123]:
#create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [124]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [125]:
#create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [126]:
ones.dtype

torch.float32

In [127]:
random_tensor.dtype

torch.float32

##creating a range of tensors and tensors-like

In [128]:
#use torch.range() and get deprecated message(will be removed in a future release), use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [129]:
#creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#Tensor datatypes
**Note: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:**
1. Tensors not right datatype
2. Tensors not right shape (dimensions)
3. Tensors not on the right device (CPU vs GPU)


In [130]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what dtype is the tensor (e.g. float32 or float16)
                               device=None, #what device is your tensor on (CPU or GPU)
                               requires_grad=False) #whether or not to track gradients with tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [131]:
float_32_tensor.dtype

torch.float32

In [132]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [133]:
float_32_tensor*float_16_tensor #sometimes pytorch automatically converts to the safer, higher precision dtype (mostly float32)

tensor([ 9., 36., 81.])

In [134]:
int_32_tensor = torch.tensor([3,4,5], dtype=torch.int32)
int_32_tensor

tensor([3, 4, 5], dtype=torch.int32)

In [135]:
float_32_tensor * int_32_tensor

tensor([ 9., 24., 45.])

#Getting information from tensors (tensor attributes)

Tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype
Tensors not right shape - to get shape from a tensor, can use tensor.shape
Tensors not on the right device - to get device from a tensor, can use tensor.device

In [136]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3912, 0.4967, 0.0328, 0.2478],
        [0.1066, 0.7805, 0.9033, 0.7515],
        [0.7061, 0.3669, 0.1746, 0.9632]])

In [137]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3912, 0.4967, 0.0328, 0.2478],
        [0.1066, 0.7805, 0.9033, 0.7515],
        [0.7061, 0.3669, 0.1746, 0.9632]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


#Manipulating Tensors (tensor operations)
Tensor opertions include:

* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [138]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [139]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [140]:
tensor

tensor([1, 2, 3])

In [141]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [142]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [143]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix mutliplication (dot product)

There are two main rules that performing matrix mutliplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [144]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [145]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [146]:
tensor

tensor([1, 2, 3])

In [147]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [148]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 878 µs, sys: 0 ns, total: 878 µs
Wall time: 754 µs


In [149]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 477 µs, sys: 0 ns, total: 477 µs
Wall time: 450 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [150]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [156]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [155]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [153]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [154]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [152]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [157]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [158]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [159]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [160]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [161]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))