<a href="https://colab.research.google.com/github/UmayaJayasuriya/PyTorch_Practice/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


##Introduction to Tensors

Creating tensors

In [ ]:
#scalaar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
MATRIX = torch.tensor([[7,8,4],
                       [9,10,3]])
MATRIX

tensor([[ 7,  8,  4],
        [ 9, 10,  3]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8, 4])

In [ ]:
MATRIX.shape

torch.Size([2, 3])

In [ ]:
#tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR[0,1]

tensor([4, 5, 6])

In [ ]:
TENSOR[0,1,2]

tensor(6)

In [ ]:
TENSOR2 = torch.tensor([[[1,2],[2,3]],
                        [[3,4],[4,5]],
                         [[5,6],[6,7]]])
TENSOR2

tensor([[[1, 2],
         [2, 3]],

        [[3, 4],
         [4, 5]],

        [[5, 6],
         [6, 7]]])

In [ ]:
TENSOR2[0,0,1]

tensor(2)

#Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9880, 0.6779, 0.8141, 0.7389],
        [0.3053, 0.2965, 0.0076, 0.9685],
        [0.6846, 0.6624, 0.2065, 0.3856]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) #height, width ,color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

#Zeros and Ones

In [ ]:
#create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

##creating a range of tensors and tensors-like

In [ ]:
#use torch.range() and get deprecated message(will be removed in a future release), use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#Tensor datatypes
**Note: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:**
1. Tensors not right datatype
2. Tensors not right shape (dimensions)
3. Tensors not on the right device (CPU vs GPU)


In [ ]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what dtype is the tensor (e.g. float32 or float16)
                               device=None, #what device is your tensor on (CPU or GPU)
                               requires_grad=False) #whether or not to track gradients with tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor*float_16_tensor #sometimes pytorch automatically converts to the safer, higher precision dtype (mostly float32)

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,4,5], dtype=torch.int32)
int_32_tensor

tensor([3, 4, 5], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

NameError: name 'float_32_tensor' is not defined

#Getting information from tensors (tensor attributes)

Tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype
Tensors not right shape - to get shape from a tensor, can use tensor.shape
Tensors not on the right device - to get device from a tensor, can use tensor.device